apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:32:35.548882086+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 720fdd8077049b7c706fadbae1cf3b1d1c9471a7d3ee257fc6476348a00725e9
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.549038651+01:00"
    description: A Helm chart for Kubernetes
    digest: b307f821fc2fe94817a00b37932de2965c4cd4f6ca692a4889d0f719485fc395
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.549208492+01:00"
    description: Hello World Configmap App
    digest: edff71d2a2a4e02ec3d35f8f39c4952db6023426472d1ede8b40c3dc177f6827
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.549373292+01:00"
    description: Hello World Secret App
    digest: e8d0e1808ace55a90105b20342cffbb3ebab3837a04077d4b0b421ddb46e84f0
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:32:35.552049575+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: db100f9056d11960f0653f2ae07263b462bbbeda592d79d80ca517eb18f9f95b
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.55222727+01:00"
    description: A Helm chart for Kubernetes
    digest: df140e9a38d2a43b69f17e348bde1740ebb9890b26c826f4369ab21af1d65e58
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.552398293+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 7e3c67437820d7f85b2a388168617ab297391a1e560ef78baf9b5ca8c00907e0
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:32:35.552590456+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 92072279d36d76f28f568d5476ea202329fa8f2c8735c8b38ede355a07a802b8
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:32:35.552760417+01:00"
    description: SpringBoot UserList
    digest: 37b9ff79c4e87513f86d9e7a5f4acae2f955d584480d7cebdfc42349fedac609
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:32:35.5529269+01:00"
    description: Userlist Frontend
    digest: 2422a2b4a49168fc0c237a597fd26395039cd7ae5d64ae8413e04642fe6a10ab
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:32:35.553689493+01:00"
    description: Voting Application Demo - FrontEnd
    digest: e822afd8b6973c2a19b98306838e5780c894cc0a5676e1bc6a70e49d3c2b2a53
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:32:35.548640377+01:00"
