apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:06:32.220487839+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 4c81f2feb62fc2a6aa147b38d28612917ae9e57fa8696a0e4b21f9409528050a
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.22067912+01:00"
    description: A Helm chart for Kubernetes
    digest: 5dc805740a4a5410628bddce9cf58f8d08b4a3b7490decc624a8d409c723857e
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.220859131+01:00"
    description: Hello World Configmap App
    digest: 42972dbea21eabc78dc6a8e96d08bb79b02fe5804f3a26cd33c666e4fa0b3142
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.221029501+01:00"
    description: Hello World Secret App
    digest: 434e4d01e2b6177ff0dcc7128ff1e164bd31f29b5ac222c50e4cff1f0cf459a4
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:06:32.222937482+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: b816b80a88c34b609db651d2bfff852322b8f83ee5c15f2566a047909feba014
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.223107432+01:00"
    description: A Helm chart for Kubernetes
    digest: fe492b8d709def36f8289086f7843e47872d3d35811134fb8a8bc3a5eb95349d
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.223392626+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 7a5a1f68e69e0a3363a1aef934be4746d5b3578213832e32078f6908a1f0e238
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:06:32.22377008+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: d19e8662c2566fb36473dfb5195f20ff5d13447e7e6adaec8d710bf01eacc4c5
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:06:32.224055135+01:00"
    description: SpringBoot UserList
    digest: 8307a8bf71d0208a32785d49fbf52e50d26807cc4f30f08d06f67965b303b646
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:06:32.224540277+01:00"
    description: Userlist Frontend
    digest: 5ad9ba9e633c607059817261a33a6a3a986039246de8901fe9e27c26b1986d5d
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:06:32.22531355+01:00"
    description: Voting Application Demo - FrontEnd
    digest: 7e7edcf75156e62bddbe844ba3929e836762c0ed56cba6fc583d54a78280d315
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:06:32.220189058+01:00"
