apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:42:04.239782635+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 82770c2af4117529bf4a58a3cc911e97bc86f43b66dfe058ae096bb388ef36e8
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.239935231+01:00"
    description: A Helm chart for Kubernetes
    digest: fc18f04ec920f3475ede721cb4180ca02a995978051ad241c22941bed019a73b
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.240129939+01:00"
    description: Hello World Configmap App
    digest: b3e14513f77fd32177ed6c7cee249b7484ba8f3457baa9f6722dbd3879c7573b
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.240322935+01:00"
    description: Hello World Secret App
    digest: bc6c817d4a5d3a654568cf8aeb7636235d994f32ea6e6a21e990528c8d5b1c3f
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:42:04.242237585+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: 3b66909619bc02c7d627597a3319c1a2ce4104649fe7d07e4f593e8aa6621ccf
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.242397055+01:00"
    description: A Helm chart for Kubernetes
    digest: 5a8c3ec75276ef9b12c6d9ddee5f4395269314d74a57b78a581b1b21dc3fab1b
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.242583337+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 6b89bb66ad965fab7f24822e5b1aa5f416b4f5d82c8554c7c14d5e9b6fd861ed
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:42:04.24279056+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: f1fe6800ccd1295721ecd76658b7b98509805c21b6f2d85764c342ccbb7a9b47
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:42:04.242984817+01:00"
    description: SpringBoot UserList
    digest: 689afb291882619f1d0f96d826156a242fa52d1c79a44b411e8cc42e287ba9c8
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:42:04.243523293+01:00"
    description: Userlist Frontend
    digest: 0d25384296eaf1a28f5a7944eb3f1ef8e41a5c017ed028ea8d12c543b273b160
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:42:04.244681275+01:00"
    description: Voting Application Demo - FrontEnd
    digest: 0a125ec59f380c530a404dd85dc2b127bbe6bd25288e25bed094ca78d3be4207
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:42:04.239534492+01:00"
