apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:37:29.430814653+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 6ee1614ef4067253866d78234560330bfeb2e74ad14b5d2f222ad3d35887a8f7
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.43098922+01:00"
    description: A Helm chart for Kubernetes
    digest: f816ffb0cafd2529777d32a5aefc398bb4bb161243cb17fdf33f4f4060692c2c
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.431207355+01:00"
    description: Hello World Configmap App
    digest: 52e3dc33ef3ff963cae792f083376946b5414da1ab4f9ed9cf44a4ab66d9e9e8
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.43137505+01:00"
    description: Hello World Secret App
    digest: 21044cfe7069480df7fc724565eb56a55ca7749033d5ea0ae158e0d1eb0d8ee3
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:37:29.433422559+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: 0b6dd7a9ff30c9d51df8d491834d8c1d9b1cbabe464d09de66607108e12e629d
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.433594242+01:00"
    description: A Helm chart for Kubernetes
    digest: 04c79af981dfb1478e678a5f33fb793ebfcd2a7131e87d5ea28bf90c8ce8904b
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.433785404+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: d425907f6c9d056810d2ffb424b857566b72090cf1ba5f05821e36bb6cbca3c1
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:37:29.433978238+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: f16c0f02acc6ab016a0d8038298f0a0ad9507166c352d36de2198e98888e2454
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:37:29.434168317+01:00"
    description: SpringBoot UserList
    digest: 717820628ef4d2f3fb23fae88bfce28d918afa560db3ef2fc0e331889aa3cd8f
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:37:29.434698057+01:00"
    description: Userlist Frontend
    digest: 1ee99a7bb86ed174fb23b2f2f3cc3d39fae12cde3758295e89a2003dd0a6c33d
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:37:29.436151882+01:00"
    description: Voting Application Demo - FrontEnd
    digest: 672b7f81c43bbad3ea4a504e354c5418b37eaf3887cbd0dbbde6a4ada8e74c36
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:37:29.430573233+01:00"
