apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:17:56.558753529+01:00"
    description: 'N-Able Training: client-ip app'
    digest: b238047f3906536bb6ab91bd7a2aa6cb5311d2a57cf0a57583d29137eff8470d
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.558959609+01:00"
    description: A Helm chart for Kubernetes
    digest: f2ed4cf069c9df701f3426050b98deb94f78c9940358b8d3396bfde0887fc6f3
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.559175459+01:00"
    description: Hello World Configmap App
    digest: 13260010bc79a83936febb4534ff892ea48c4ca2a42c0010cdd83c504fad681c
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.559370608+01:00"
    description: Hello World Secret App
    digest: d5a8722dd83b961782e2289e9eca48be67f1649b870ad06e47b8730963d92a7c
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:17:56.562544999+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: c3bb9d5968e6f45ebe8ebaa094e5c51560af56265fe6e6e6e2b0ab05138d375d
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.562783854+01:00"
    description: A Helm chart for Kubernetes
    digest: b4207a52babb0f1361486e543feed057807eef17c53f6a2ee92c14281bcd8ad2
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.563024181+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: aea233269fc27a13fce691e6306a93eff0eb7890d2bf70a1d8f7559778815978
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:17:56.563272314+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 2ed320d52f316bd4df70b29fb2b10e4dfd5c71c505480b5bcc5219d79e6d2ad6
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:17:56.563539182+01:00"
    description: SpringBoot UserList
    digest: 5ef58a1286743c35134233a5be542d94f5961bf9c56b0c8050ffc0b21c191bd5
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:17:56.563790561+01:00"
    description: Userlist Frontend
    digest: 6f50fd359df7f05e1a9c5cca02417b3836957592acf5e9829bd3d3d7ecf3f8b3
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:17:56.565057384+01:00"
    description: Voting Application Demo - FrontEnd
    digest: 6472afedd5c815a1212f6d6cc03d3dfeda2617098728b3aa9a7d35289fdaefe5
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:17:56.558441302+01:00"
