apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:21:25.661922019+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 7f10b1e9f32a04bf13339cb55506f251a904654e4815688df16a60abc014d388
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.662104925+01:00"
    description: A Helm chart for Kubernetes
    digest: 571ab7933d33b4871058d4c24a51b06d1ab342048dfc23bd26365dcc5b6f930b
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.662300385+01:00"
    description: Hello World Configmap App
    digest: 07736a46ef6eb38283b84a34da73de27d6edcf741ee8497ad2d121b99cfbed8b
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.662517527+01:00"
    description: Hello World Secret App
    digest: 2c7407a25367f53db36e4b7156d877b805436bd6b1e025f955da5cfff6e97e09
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:21:25.66492127+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: a943ae9e4ee7c44734b2a89c302899247cc8f4d8f91a84233f9803865de3cfe2
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.665078896+01:00"
    description: A Helm chart for Kubernetes
    digest: 7d2568e56453e0e3ca1be8268a928039b0be6c8698d8d692cc3ced1ec212156e
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.665253857+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 42190d57698e778d4a5a79556466c51181ca6f1362f8328b0c28aa7fbc5bc875
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:21:25.665425771+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 2974f231c90da0e4683514c7f7364b211ef1aab39d9fe68dcd92b6633015ac62
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:21:25.665606992+01:00"
    description: SpringBoot UserList
    digest: 168430e1b799a190ef4badc914093e4ee2ca73dcef6348a1a4485f382207cd84
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:21:25.665776141+01:00"
    description: Userlist Frontend
    digest: ce8a56401530f103dab0062714946904de7b924b95e91adde8f89fe84bf1d89c
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:21:25.666571689+01:00"
    description: Voting Application Demo - FrontEnd
    digest: 8795f8d9d5522b3038a9e09dd4efe6903eb933952b694e09a9bae5229ab74ade
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:21:25.661620073+01:00"
