apiVersion: v1
entries:
  clientip:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:27:29.603661634+01:00"
    description: 'N-Able Training: client-ip app'
    digest: 2477dae0b5826d6cbef805e681b7ad5897a5b89bb0ba2b5930b581a3405eac9b
    name: clientip
    urls:
    - clientip-0.2.1.tgz
    version: 0.2.1
  hello-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.603841753+01:00"
    description: A Helm chart for Kubernetes
    digest: 83ed44cacb51463433391e67879fac8fe3c8359370e341277b55287a72cfc049
    name: hello-svc
    urls:
    - hello-svc-0.1.0.tgz
    version: 0.1.0
  hello-world-configmap:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.604025611+01:00"
    description: Hello World Configmap App
    digest: 175e7d5c9f48c35704fbe8d0fb2942a7a345edf4de3197d10bb593b0709095cd
    name: hello-world-configmap
    urls:
    - hello-world-configmap-1.0.0.tgz
    version: 1.0.0
  hello-world-secret:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.604198106+01:00"
    description: Hello World Secret App
    digest: a45d2bafd632baa5d027bd9d8705a3c99a487ef064395f50fcb26521c0837d54
    name: hello-world-secret
    urls:
    - hello-world-secret-1.0.0.tgz
    version: 1.0.0
  keycloak:
  - apiVersion: v1
    appVersion: 10.0.0
    created: "2026-01-29T20:27:29.606076689+01:00"
    dependencies:
    - condition: keycloak.persistence.deployPostgres
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.5
    description: Open Source Identity and Access Management For Modern Applications
      and Services
    digest: 141a56742b73b416d6e1bedef4f4acc90741aab17ea903120d95985ee3a065ab
    home: https://www.keycloak.org/
    icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
    keywords:
    - sso
    - idm
    - openid connect
    - saml
    - kerberos
    - ldap
    maintainers:
    - email: unguiculus@gmail.com
      name: unguiculus
    - email: thomas.darimont+github@gmail.com
      name: thomasdarimont
    name: keycloak
    sources:
    - https://github.com/codecentric/helm-charts
    - https://github.com/jboss-dockerfiles/keycloak
    urls:
    - keycloak-8.2.1.tgz
    version: 8.2.1
  quote-svc:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.606226661+01:00"
    description: A Helm chart for Kubernetes
    digest: 4dc8f3b780abae5aad799366a9a92045a6a42a7798caf332531b7fc289a25450
    name: quote-svc
    urls:
    - quote-svc-0.1.0.tgz
    version: 0.1.0
  sso-app-backend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.606388445+01:00"
    description: 'N-Able Training: Subject Single Sign On - Backoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: 97e6eea1ecbf43aaa11af5c076862fd87529ade47f5a48eea9a5b1446ecd6c3a
    name: sso-app-backend
    urls:
    - sso-app-backend-0.1.0.tgz
    version: 0.1.0
  sso-app-frontend:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2026-01-29T20:27:29.606577422+01:00"
    description: 'N-Able Training: Subject Single Sign On - Frontoffice Application.
      Example of how to add RBAC to applictions using OAuth2 SSO.'
    digest: fa172ac727474f7b6648cdbbea6aae3162d2b01a15e53b303dabbbf7918a7799
    name: sso-app-frontend
    urls:
    - sso-app-frontend-0.1.0.tgz
    version: 0.1.0
  ul:
  - apiVersion: v1
    appVersion: "0.2"
    created: "2026-01-29T20:27:29.606737033+01:00"
    description: SpringBoot UserList
    digest: a358ff1430b0df0e712cca872422f0eada801ee8e94bc50662a2c6673479d689
    name: ul
    urls:
    - ul-0.2.1.tgz
    version: 0.2.1
  ul-frontend:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:27:29.606896102+01:00"
    description: Userlist Frontend
    digest: 38c3f0a5c79024bb4a358a260b8378c63f1f0861d58fabd400592ef55547de7a
    name: ul-frontend
    urls:
    - ul-frontend-1.0.0.tgz
    version: 1.0.0
  vote-front:
  - annotations:
      category: Demo
    apiVersion: v1
    appVersion: "2.0"
    created: "2026-01-29T20:27:29.608047701+01:00"
    description: Voting Application Demo - FrontEnd
    digest: e09e9210a85cc51a00bd2918ac219a8e3f3801f01ef4961f56f58655918428c2
    name: vote-front
    urls:
    - vote-front-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-29T20:27:29.603384785+01:00"
